
CREATE INDEX IX_03_DEMAND_SHIP_STATUS
    ON TEAM_03_DEMAND (SHIP_ID, DEMAND_STATUS);

CREATE INDEX IX_03_DEMAND_LINE_DEMAND
    ON TEAM_03_DEMAND_LINE (DEMAND_ID);

CREATE INDEX IX_03_RFQ_VENDOR_VENDOR
    ON TEAM_03_RFQ_VENDOR (VENDOR_ID, INVITATION_STATUS);

CREATE INDEX IX_03_QUOTE_LINE_QUOTE
    ON TEAM_03_QUOTATION_LINE (QUOTATION_ID);

CREATE INDEX IX_03_PO_VENDOR_STATUS
    ON TEAM_03_PURCHASE_ORDER (VENDOR_ID, PO_STATUS);

CREATE INDEX IX_03_PO_LINE_PO
    ON TEAM_03_PURCHASE_ORDER_LINE (PO_ID);

CREATE INDEX IX_03_DELIVERY_PO_STATUS
    ON TEAM_03_DELIVERY (PO_ID, DELIVERY_STATUS);

CREATE INDEX IX_03_DELIVERY_LINE_DELIVERY
    ON TEAM_03_DELIVERY_LINE (DELIVERY_ID);

CREATE INDEX IX_03_NOTIFICATION_USER_READ
    ON TEAM_03_NOTIFICATION (USER_ID, IS_READ, CREATED_AT);

CREATE INDEX IX_03_ACTIVITY_ENTITY
    ON TEAM_03_ACTIVITY_LOG (ENTITY_TYPE, ENTITY_ID, ACTION_AT);
