-- Project Code : AHM_2026_03
-- Purpose      : Permanently clear all TEAM_03_ data and drop all TEAM_03_ tables.
--
-- WARNING: This is destructive. It deletes all project records and permanently
-- drops the tables. Do not run it in a production schema unless you have a backup.
--
-- The DELETE statements are arranged from child tables to parent tables so that
-- foreign-key constraints are respected. The DROP blocks are re-runnable: a
-- missing table is ignored, but every other error is raised.

--------------------------------------------------------------------------------
-- STEP 1: CLEAR ALL DATA
--------------------------------------------------------------------------------

DELETE FROM TEAM_03_ACTIVITY_LOG;
DELETE FROM TEAM_03_NOTIFICATION;
DELETE FROM TEAM_03_VENDOR_RATING;
DELETE FROM TEAM_03_DELIVERY_LINE;
DELETE FROM TEAM_03_DELIVERY;
DELETE FROM TEAM_03_PURCHASE_ORDER_LINE;
DELETE FROM TEAM_03_PURCHASE_ORDER;
DELETE FROM TEAM_03_QUOTATION_LINE;
DELETE FROM TEAM_03_QUOTATION;
DELETE FROM TEAM_03_RFQ_VENDOR;
DELETE FROM TEAM_03_DEMAND_LINE;
DELETE FROM TEAM_03_DEMAND;
DELETE FROM TEAM_03_ITEM;
DELETE FROM TEAM_03_ITEM_CATEGORY;
DELETE FROM TEAM_03_VENDOR;
DELETE FROM TEAM_03_SHIP;
DELETE FROM TEAM_03_APP_USER;

COMMIT;

--------------------------------------------------------------------------------
-- STEP 2: DROP ALL TABLES
-- CASCADE CONSTRAINTS removes dependent constraints.
-- PURGE bypasses Oracle's recycle bin, so the dropped tables cannot be restored.
--------------------------------------------------------------------------------

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEAM_03_ACTIVITY_LOG CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEAM_03_NOTIFICATION CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEAM_03_VENDOR_RATING CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEAM_03_DELIVERY_LINE CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEAM_03_DELIVERY CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEAM_03_PURCHASE_ORDER_LINE CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEAM_03_PURCHASE_ORDER CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEAM_03_QUOTATION_LINE CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEAM_03_QUOTATION CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEAM_03_RFQ_VENDOR CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEAM_03_DEMAND_LINE CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEAM_03_DEMAND CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEAM_03_ITEM CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEAM_03_ITEM_CATEGORY CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEAM_03_VENDOR CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEAM_03_SHIP CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEAM_03_APP_USER CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- All TEAM_03_ tables have now been permanently removed.
