
INSERT INTO TEAM_03_APP_USER
    (USER_ID, USERNAME, PASSWORD_HASH, FULL_NAME, EMAIL, USER_TYPE)
VALUES
    (1, 'admin.03', 'demo_hash_replace_before_production', 'System Administrator',
     'admin@shipstore.com', 'ADMIN');

INSERT INTO TEAM_03_APP_USER
    (USER_ID, USERNAME, PASSWORD_HASH, FULL_NAME, EMAIL, USER_TYPE)
VALUES
    (2, 'anita.ship', 'demo_hash_replace_before_production', 'Anita Sharma',
     'anita.sharma@mvoceanstar.com', 'SHIP_USER');

INSERT INTO TEAM_03_APP_USER
    (USER_ID, USERNAME, PASSWORD_HASH, FULL_NAME, EMAIL, USER_TYPE)
VALUES
    (3, 'marine.vendor', 'demo_hash_replace_before_production', 'Raj Mehta',
     'raj@marineutility.com', 'VENDOR_USER');

INSERT INTO TEAM_03_APP_USER
    (USER_ID, USERNAME, PASSWORD_HASH, FULL_NAME, EMAIL, USER_TYPE)
VALUES
    (4, 'oceanic.vendor', 'demo_hash_replace_before_production', 'Lim Wei',
     'lim@oceanicchandlers.com', 'VENDOR_USER');

INSERT INTO TEAM_03_SHIP
    (SHIP_ID, APP_USER_ID, SHIP_CODE, SHIP_NAME, IMO_NUMBER)
VALUES
    (1, 2, 'MV-SEA-001', 'MV Ocean Star', 'IMO9876543');

INSERT INTO TEAM_03_VENDOR
    (VENDOR_ID, APP_USER_ID, VENDOR_CODE, VENDOR_NAME, EMAIL, PHONE, ADDRESS,
     CITY, COUNTRY, AVERAGE_RATING, TOTAL_RATINGS)
VALUES
    (1, 3, 'VEN-001', 'Marine Utility Supplies Pvt Ltd', 'sales@marineutility.com',
     '+91-22-5550101', '12 Harbour Road', 'Mumbai', 'India', 5, 1);

INSERT INTO TEAM_03_VENDOR
    (VENDOR_ID, APP_USER_ID, VENDOR_CODE, VENDOR_NAME, EMAIL, PHONE, ADDRESS,
     CITY, COUNTRY)
VALUES
    (2, 4, 'VEN-002', 'Oceanic Ship Chandlers', 'sales@oceanicchandlers.com',
     '+65-5550202', '8 Marina Bay Avenue', 'Singapore', 'Singapore');

INSERT INTO TEAM_03_ITEM_CATEGORY (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION)
VALUES (1, 'Cleaning Materials', 'Cleaning and housekeeping items');

INSERT INTO TEAM_03_ITEM_CATEGORY (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION)
VALUES (2, 'Stationery', 'Office and stationery supplies');

INSERT INTO TEAM_03_ITEM_CATEGORY (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION)
VALUES (3, 'Safety Items', 'Personal protective and basic safety supplies');

INSERT INTO TEAM_03_ITEM
    (ITEM_ID, ITEM_CODE, ITEM_NAME, CATEGORY_ID, UNIT_OF_MEASURE, SPECIFICATION)
VALUES
    (1, 'CLN-001', 'Floor Cleaning Liquid', 1, 'CAN', '5 litre can');

INSERT INTO TEAM_03_ITEM
    (ITEM_ID, ITEM_CODE, ITEM_NAME, CATEGORY_ID, UNIT_OF_MEASURE, SPECIFICATION)
VALUES
    (2, 'STA-001', 'A4 Printing Paper', 2, 'REAM', '80 GSM, 500 sheets');

INSERT INTO TEAM_03_ITEM
    (ITEM_ID, ITEM_CODE, ITEM_NAME, CATEGORY_ID, UNIT_OF_MEASURE, SPECIFICATION)
VALUES
    (3, 'SAF-001', 'Safety Gloves', 3, 'PAIR', 'Industrial nitrile gloves');

INSERT INTO TEAM_03_DEMAND
    (DEMAND_ID, DEMAND_NO, SHIP_ID, CREATED_BY_USER_ID, REQUIRED_DELIVERY_DATE,
     DELIVERY_LOCATION, INSTRUCTIONS, DEMAND_STATUS, SELECTED_DATE, CLOSED_DATE)
VALUES
    (1, 'DEM-2026-0001', 1, 2, DATE '2026-09-20', 'Port of Mumbai',
     'Deliver the goods at the vessel berth and inform the ship user before arrival.',
     'CLOSED', TO_TIMESTAMP('2026-09-15 11:30:00', 'YYYY-MM-DD HH24:MI:SS'),
     TO_TIMESTAMP('2026-09-20 15:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TEAM_03_DEMAND_LINE
    (DEMAND_LINE_ID, DEMAND_ID, ITEM_ID, REQUESTED_QTY, UNIT_OF_MEASURE)
VALUES (1, 1, 1, 30, 'CAN');

INSERT INTO TEAM_03_DEMAND_LINE
    (DEMAND_LINE_ID, DEMAND_ID, ITEM_ID, REQUESTED_QTY, UNIT_OF_MEASURE)
VALUES (2, 1, 2, 20, 'REAM');

INSERT INTO TEAM_03_DEMAND_LINE
    (DEMAND_LINE_ID, DEMAND_ID, ITEM_ID, REQUESTED_QTY, UNIT_OF_MEASURE)
VALUES (3, 1, 3, 50, 'PAIR');

INSERT INTO TEAM_03_RFQ_VENDOR
    (RFQ_VENDOR_ID, DEMAND_ID, VENDOR_ID, QUOTATION_DUE_DATE, INVITATION_STATUS)
VALUES (1, 1, 1, DATE '2026-09-15', 'QUOTED');

INSERT INTO TEAM_03_RFQ_VENDOR
    (RFQ_VENDOR_ID, DEMAND_ID, VENDOR_ID, QUOTATION_DUE_DATE, INVITATION_STATUS)
VALUES (2, 1, 2, DATE '2026-09-15', 'QUOTED');

INSERT INTO TEAM_03_QUOTATION
    (QUOTATION_ID, QUOTATION_NO, RFQ_VENDOR_ID, QUOTATION_DATE, VALID_UNTIL,
     EXPECTED_DELIVERY_DATE, DELIVERY_CHARGE, TAX_AMOUNT, TOTAL_AMOUNT,
     PAYMENT_TERMS, QUOTATION_STATUS, SUBMITTED_AT)
VALUES
    (1, 'QTN-2026-0045', 1, DATE '2026-09-15', DATE '2026-09-25',
     DATE '2026-09-18', 1500, 0, 40900, 'Payment within 30 days', 'SELECTED',
     TO_TIMESTAMP('2026-09-15 09:15:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TEAM_03_QUOTATION
    (QUOTATION_ID, QUOTATION_NO, RFQ_VENDOR_ID, QUOTATION_DATE, VALID_UNTIL,
     EXPECTED_DELIVERY_DATE, DELIVERY_CHARGE, TAX_AMOUNT, TOTAL_AMOUNT,
     PAYMENT_TERMS, QUOTATION_STATUS, SUBMITTED_AT)
VALUES
    (2, 'QTN-2026-0046', 2, DATE '2026-09-15', DATE '2026-09-25',
     DATE '2026-09-21', 2000, 0, 39400, 'Payment within 15 days', 'REJECTED',
     TO_TIMESTAMP('2026-09-15 10:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TEAM_03_QUOTATION_LINE
    (QUOTATION_LINE_ID, QUOTATION_ID, DEMAND_LINE_ID, AVAILABLE_QTY, UNIT_PRICE,
     LINE_TOTAL, EXPECTED_DELIVERY_DATE)
VALUES (1, 1, 1, 30, 850, 25500, DATE '2026-09-18');

INSERT INTO TEAM_03_QUOTATION_LINE
    (QUOTATION_LINE_ID, QUOTATION_ID, DEMAND_LINE_ID, AVAILABLE_QTY, UNIT_PRICE,
     LINE_TOTAL, EXPECTED_DELIVERY_DATE)
VALUES (2, 1, 2, 20, 320, 6400, DATE '2026-09-18');

INSERT INTO TEAM_03_QUOTATION_LINE
    (QUOTATION_LINE_ID, QUOTATION_ID, DEMAND_LINE_ID, AVAILABLE_QTY, UNIT_PRICE,
     LINE_TOTAL, EXPECTED_DELIVERY_DATE)
VALUES (3, 1, 3, 50, 150, 7500, DATE '2026-09-18');

INSERT INTO TEAM_03_QUOTATION_LINE
    (QUOTATION_LINE_ID, QUOTATION_ID, DEMAND_LINE_ID, AVAILABLE_QTY, UNIT_PRICE,
     LINE_TOTAL, EXPECTED_DELIVERY_DATE, REMARKS)
VALUES (4, 2, 1, 30, 820, 24600, DATE '2026-09-21', 'Delivery after required date');

INSERT INTO TEAM_03_QUOTATION_LINE
    (QUOTATION_LINE_ID, QUOTATION_ID, DEMAND_LINE_ID, AVAILABLE_QTY, UNIT_PRICE,
     LINE_TOTAL, EXPECTED_DELIVERY_DATE, REMARKS)
VALUES (5, 2, 2, 20, 350, 7000, DATE '2026-09-21', 'Delivery after required date');

INSERT INTO TEAM_03_QUOTATION_LINE
    (QUOTATION_LINE_ID, QUOTATION_ID, DEMAND_LINE_ID, AVAILABLE_QTY, UNIT_PRICE,
     LINE_TOTAL, EXPECTED_DELIVERY_DATE, REMARKS)
VALUES (6, 2, 3, 40, 145, 5800, DATE '2026-09-21', 'Only 40 pairs available');

INSERT INTO TEAM_03_PURCHASE_ORDER
    (PO_ID, PO_NO, DEMAND_ID, QUOTATION_ID, VENDOR_ID, CREATED_BY_USER_ID,
     PO_DATE, EXPECTED_DELIVERY_DATE, DELIVERY_LOCATION, CURRENCY_CODE,
     SUBTOTAL_AMOUNT, DELIVERY_CHARGE, TAX_AMOUNT, TOTAL_AMOUNT, PAYMENT_TERMS,
     PO_STATUS)
VALUES
    (1, 'PO-2026-0012', 1, 1, 1, 2, DATE '2026-09-15', DATE '2026-09-18',
     'Port of Mumbai', 'USD', 39400, 1500, 0, 40900, 'Payment within 30 days',
     'DELIVERED');

INSERT INTO TEAM_03_PURCHASE_ORDER_LINE
    (PO_LINE_ID, PO_ID, QUOTATION_LINE_ID, ITEM_ID, ORDERED_QTY, UNIT_OF_MEASURE,
     UNIT_PRICE, LINE_TOTAL)
VALUES (1, 1, 1, 1, 30, 'CAN', 850, 25500);

INSERT INTO TEAM_03_PURCHASE_ORDER_LINE
    (PO_LINE_ID, PO_ID, QUOTATION_LINE_ID, ITEM_ID, ORDERED_QTY, UNIT_OF_MEASURE,
     UNIT_PRICE, LINE_TOTAL)
VALUES (2, 1, 2, 2, 20, 'REAM', 320, 6400);

INSERT INTO TEAM_03_PURCHASE_ORDER_LINE
    (PO_LINE_ID, PO_ID, QUOTATION_LINE_ID, ITEM_ID, ORDERED_QTY, UNIT_OF_MEASURE,
     UNIT_PRICE, LINE_TOTAL)
VALUES (3, 1, 3, 3, 50, 'PAIR', 150, 7500);

INSERT INTO TEAM_03_DELIVERY
    (DELIVERY_ID, DELIVERY_NO, PO_ID, DELIVERY_STATUS, TRACKING_REFERENCE,
     TRANSPORTER_NAME, EXPECTED_DELIVERY_DATE, ACTUAL_DELIVERY_DATE,
     STATUS_REMARKS, LAST_UPDATED_BY_USER_ID)
VALUES
    (1, 'DEL-2026-0008', 1, 'DELIVERED', 'MUM-TRACK-456', 'Harbour Logistics',
     DATE '2026-09-18', DATE '2026-09-18',
     'All items delivered to MV Ocean Star at Port of Mumbai.', 3);

INSERT INTO TEAM_03_DELIVERY_LINE
    (DELIVERY_LINE_ID, DELIVERY_ID, PO_LINE_ID, DELIVERED_QTY)
VALUES (1, 1, 1, 30);

INSERT INTO TEAM_03_DELIVERY_LINE
    (DELIVERY_LINE_ID, DELIVERY_ID, PO_LINE_ID, DELIVERED_QTY)
VALUES (2, 1, 2, 20);

INSERT INTO TEAM_03_DELIVERY_LINE
    (DELIVERY_LINE_ID, DELIVERY_ID, PO_LINE_ID, DELIVERED_QTY)
VALUES (3, 1, 3, 50);

INSERT INTO TEAM_03_VENDOR_RATING
    (RATING_ID, PO_ID, VENDOR_ID, RATED_BY_USER_ID, OVERALL_RATING, COMMENTS,
     RATED_AT)
VALUES
    (1, 1, 1, 2, 5, 'All requested goods were delivered on time and in good condition.',
     TO_TIMESTAMP('2026-09-20 15:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TEAM_03_NOTIFICATION
    (NOTIFICATION_ID, USER_ID, NOTIFICATION_TYPE, TITLE, MESSAGE, REFERENCE_TYPE,
     REFERENCE_ID, IS_READ, IS_POPUP_SHOWN)
VALUES
    (1, 3, 'RFQ_RECEIVED', 'New RFQ Received',
     'Demand DEM-2026-0001 is available for your quotation.', 'DEMAND', 1, 'Y', 'N');

INSERT INTO TEAM_03_NOTIFICATION
    (NOTIFICATION_ID, USER_ID, NOTIFICATION_TYPE, TITLE, MESSAGE, REFERENCE_TYPE,
     REFERENCE_ID, IS_READ, IS_POPUP_SHOWN)
VALUES
    (2, 2, 'QUOTATION_SUBMITTED', 'Quotation Received',
     'Marine Utility Supplies submitted quotation QTN-2026-0045.', 'QUOTATION', 1, 'Y', 'N');

INSERT INTO TEAM_03_NOTIFICATION
    (NOTIFICATION_ID, USER_ID, NOTIFICATION_TYPE, TITLE, MESSAGE, REFERENCE_TYPE,
     REFERENCE_ID, IS_READ, IS_POPUP_SHOWN)
VALUES
    (3, 3, 'QUOTATION_SELECTED', 'Quotation Selected',
     'Your quotation was selected. Purchase order PO-2026-0012 has been issued.',
     'PURCHASE_ORDER', 1, 'Y', 'N');

INSERT INTO TEAM_03_NOTIFICATION
    (NOTIFICATION_ID, USER_ID, NOTIFICATION_TYPE, TITLE, MESSAGE, REFERENCE_TYPE,
     REFERENCE_ID, IS_READ, IS_POPUP_SHOWN)
VALUES
    (4, 2, 'DELIVERY_COMPLETED', 'Delivery Completed',
     'Order PO-2026-0012 has been delivered. Please rate Marine Utility Supplies.',
     'PURCHASE_ORDER', 1, 'Y', 'Y');

INSERT INTO TEAM_03_NOTIFICATION
    (NOTIFICATION_ID, USER_ID, NOTIFICATION_TYPE, TITLE, MESSAGE, REFERENCE_TYPE,
     REFERENCE_ID, IS_READ, IS_POPUP_SHOWN)
VALUES
    (5, 3, 'VENDOR_RATING_SUBMITTED', 'Vendor Rating Received',
     'MV Ocean Star gave your service a 5-star rating for PO-2026-0012.',
     'RATING', 1, 'N', 'N');

INSERT INTO TEAM_03_ACTIVITY_LOG
    (ACTIVITY_ID, ENTITY_TYPE, ENTITY_ID, ACTION_TYPE, NEW_STATUS, REMARKS,
     ACTION_BY_USER_ID, ACTION_AT)
VALUES
    (1, 'DEMAND', 1, 'CREATED', 'SUBMITTED', 'Demand DEM-2026-0001 submitted.', 2,
     TO_TIMESTAMP('2026-09-14 09:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TEAM_03_ACTIVITY_LOG
    (ACTIVITY_ID, ENTITY_TYPE, ENTITY_ID, ACTION_TYPE, OLD_STATUS, NEW_STATUS,
     REMARKS, ACTION_BY_USER_ID, ACTION_AT)
VALUES
    (2, 'QUOTATION', 1, 'STATUS_CHANGED', 'DRAFT', 'SUBMITTED',
     'Marine Utility Supplies submitted quotation QTN-2026-0045.', 3,
     TO_TIMESTAMP('2026-09-15 09:15:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TEAM_03_ACTIVITY_LOG
    (ACTIVITY_ID, ENTITY_TYPE, ENTITY_ID, ACTION_TYPE, OLD_STATUS, NEW_STATUS,
     REMARKS, ACTION_BY_USER_ID, ACTION_AT)
VALUES
    (3, 'QUOTATION', 1, 'SELECTED', 'SUBMITTED', 'SELECTED',
     'Ship user selected this quotation after comparison.', 2,
     TO_TIMESTAMP('2026-09-15 11:30:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TEAM_03_ACTIVITY_LOG
    (ACTIVITY_ID, ENTITY_TYPE, ENTITY_ID, ACTION_TYPE, NEW_STATUS, REMARKS,
     ACTION_BY_USER_ID, ACTION_AT)
VALUES
    (4, 'PURCHASE_ORDER', 1, 'CREATED', 'PENDING',
     'PO-2026-0012 created from selected quotation QTN-2026-0045.', 2,
     TO_TIMESTAMP('2026-09-15 11:31:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TEAM_03_ACTIVITY_LOG
    (ACTIVITY_ID, ENTITY_TYPE, ENTITY_ID, ACTION_TYPE, OLD_STATUS, NEW_STATUS,
     REMARKS, ACTION_BY_USER_ID, ACTION_AT)
VALUES
    (5, 'DELIVERY', 1, 'STATUS_CHANGED', 'DISPATCHED', 'DELIVERED',
     'Vendor marked the complete order as delivered.', 3,
     TO_TIMESTAMP('2026-09-18 13:20:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TEAM_03_ACTIVITY_LOG
    (ACTIVITY_ID, ENTITY_TYPE, ENTITY_ID, ACTION_TYPE, REMARKS,
     ACTION_BY_USER_ID, ACTION_AT)
VALUES
    (6, 'RATING', 1, 'CREATED', 'Ship user submitted a 5-star vendor rating.', 2,
     TO_TIMESTAMP('2026-09-20 15:00:00', 'YYYY-MM-DD HH24:MI:SS'));
